version: '3.7'

services:
    chatpad:
        container_name: chatpad
        hostname: chatpad
        build:
          context: .
          dockerfile: Dockerfile
        cap_drop:
         - ALL
        cap_add:
         - CHOWN
         - SETGID
         - SETUID
        security_opt:
         - no-new-privileges:true
        ports:
            - '127.0.0.1:8202:80'
